name: Slurm Matrix Build and Push

on:
  push:
    branches:
      - "main"
      - "dev"
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [linux/amd64, linux/arm64]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Navigate to Build Directory
        working-directory: schedmd/slurm/ubuntu-24.04
        run: |
          echo "Entered build directory"

      - name: Build and Push Images
        uses: 0x4r45h/docker-compose-ci@v0.1.0
        with:
          docker_compose_files: '-f compose.yml'
          platforms: ${{ matrix.platform }}


